### PR TITLE
Update firmware for UNL2003 stepper driver

### PR DESCRIPTION
**Pull request by REulberg**
Instead of using a stepper controller, this allows for usage of some very cheap stepper motor/driver combos, specifically the UNL2003 stepper driver. 
Conceivably one could directly drive very low power steppers such as the ones harvested from cd drives.
This WILL be quite slow -- at best 1/4 of the adafruit, since your arduino now has to handle energizing individual coils.

### CODE REVIEW

**Comment by i-make-robots** [comment]
Can you please resubmit this on the latest dev branch?  I'd like to auto-merge.  I haven't had time to resolve the conflicts and I'm bummed your patch hasn't made it in yet.

**Comment by REulberg** [comment]
Wow -- I managed to drop the ball on this pretty badly

I think I'll knock the dust off and update

**Comment by virtuoushub** [comment]
@REulberg please let me know if you need any help.

**Comment by i-make-robots** [comment]
If you're going to resubmit this, cool.  I'll close this in the mean time.

Thanks!

**Pull request closed without merging**
